# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Carlos Ronchi
email: carloshvronchi@gmail.com
description: Personal webpage.
baseurl: #"/jekyll-simple" # the subpath of your site, e.g. /blog
url: "chronchi.github.io" # the base hostname & protocol for your site
twitter_username: chronchi
github_username:  chronchi

# Build settings
markdown: kramdown
kramdown:
  input: GFM

# Third-party services
# just leave someone empty to disable it
# google_analytics:
comments: true
disqus_shortname: chronchi

# used this for post_excerpt at index_page
excerpt_separator: <!--description-->

gems:
  - jekyll-seo-tag
  - jekyll-sitemap

google_analytics: 'UA-99022056-1'

#permalink: /blog/:title.html
