baseurl:
title: Carlos Ronchi
subtitle: Personal homepage
author: carlos ronchi
description: My homepage describing my work and other stuff
name: tufte
markdown: kramdown
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
timezone: Europe/Zurich
email: carloshvronchi@gmail.com
permalink: /blog/:year/:month/:day/:slug:output_ext
excerpt_separator: <!--more-->  # you can specify your own separator, of course.
exclude: ['Gemfile', 'Gemfile.lock', 'Rakefile', 'UploadToGithub.Rakefile', 'README.md']
post:
  template: _post.txt
  extension: md
page:
  template: _page.txt
  extension: md
editor: gvim
git:
  branch: master
encoding: UTF-8
